/**
 * Unit tests for `{{NAME_KEBAB}}`.
 *
 * Generated by `tools/generator/generate.ts`. Keep the arrangement: one `describe` per
 * exported symbol, and a test name that states the behaviour rather than the method.
 */

import { describe, expect, it } from 'vitest';

import { {{NAME_PASCAL}}, is{{NAME_PASCAL}} } from '../../src/{{NAME_KEBAB}}';

describe('{{NAME_PASCAL}}', () => {
  it('constructs with no options', () => {
    const instance = new {{NAME_PASCAL}}();
    expect(instance).toBeInstanceOf({{NAME_PASCAL}});
    expect(instance.name).toBe('');
  });

  it('accepts a name', () => {
    expect(new {{NAME_PASCAL}}({ name: 'demo' }).name).toBe('demo');
  });

  it('returns itself from update, so calls chain', () => {
    const instance = new {{NAME_PASCAL}}();
    expect(instance.update(0.016)).toBe(instance);
  });

  it('disposes idempotently', () => {
    const instance = new {{NAME_PASCAL}}();
    instance.dispose();
    expect(() => instance.dispose()).not.toThrow();
  });

  it('is detected by its type guard', () => {
    expect(is{{NAME_PASCAL}}(new {{NAME_PASCAL}}())).toBe(true);
    expect(is{{NAME_PASCAL}}(null)).toBe(false);
    expect(is{{NAME_PASCAL}}({})).toBe(false);
  });
});
