/**
 * `CompressedTexture` — a texture uploaded from pre-compressed GPU blocks.
 *
 * Compressed data cannot be filtered, flipped or mip-generated on the CPU, so the
 * class disables mipmap generation and row flipping and exposes the block layout
 * through {@link CompressedFormat}. `mipmapCount` reports how many levels the
 * caller supplied, which is what a backend must upload verbatim.
 *
 * ```ts
 * const texture = new CompressedTexture(levels, 1024, 1024, CompressedFormat.Astc4x4);
 * texture.mipmapCount; // levels.length
 * ```
 *
 * @packageDocumentation
 */

import { getCompressedLevelByteSize, CompressedFormat } from './formats/CompressedFormat';
import { TextureFilter, type CompressedMipmap, type TextureSource } from './types';
import { Texture } from './Texture';

/**
 * A block-compressed texture.
 */
export class CompressedTexture extends Texture<'CompressedTexture'> {
  /** Human-readable label used in diagnostics. */
  public override readonly label = 'CompressedTexture' as const;

  /** Block layout of the data. */
  public compressedFormat: CompressedFormat;

  /** Mip levels, largest first. */
  public readonly levels: CompressedMipmap[] = [];

  /**
   * @param mipmaps Mip levels, largest first.
   * @param width Width of level 0, in texels.
   * @param height Height of level 0, in texels.
   * @param format Block layout; defaults to `ASTC 4x4`.
   */
  constructor(
    mipmaps: readonly CompressedMipmap[] | null = null,
    width: number = 1,
    height: number = 1,
    format: CompressedFormat = CompressedFormat.Astc4x4,
  ) {
    super(null);
    this.compressedFormat = format;
    this.generateMipmaps = false;
    this.flipY = false;
    this.unpackAlignment = 1;
    this.magFilter = TextureFilter.Linear;
    this.minFilter = TextureFilter.LinearMipmapLinear;

    if (mipmaps && mipmaps.length > 0) {
      for (const level of mipmaps) this.levels.push(level);
    } else {
      this.levels.push({ data: new Uint8Array(0), width, height });
    }
    this.syncLevel(0);
  }

  /** Number of mip levels supplied. */
  public get mipmapCount(): number {
    return this.levels.length;
  }

  /** Width of level 0, in texels. */
  public get width(): number {
    return this.levels[0]?.width ?? 1;
  }

  /** Height of level 0, in texels. */
  public get height(): number {
    return this.levels[0]?.height ?? 1;
  }

  /** Total byte size of every supplied level. */
  public get byteLength(): number {
    let total = 0;
    for (const level of this.levels) total += level.data.byteLength;
    return total;
  }

  /**
   * Replaces the mip chain.
   *
   * @param mipmaps Levels, largest first.
   * @returns This texture, for chaining.
   */
  public setMipmaps(mipmaps: readonly CompressedMipmap[]): this {
    this.levels.length = 0;
    for (const level of mipmaps) this.levels.push(level);
    if (this.levels.length === 0) {
      this.levels.push({ data: new Uint8Array(0), width: 1, height: 1 });
    }
    this.syncLevel(0);
    return this;
  }

  /**
   * Replaces one mip level.
   *
   * @param level Level index; `0` is the largest.
   * @param mipmap Replacement level.
   * @returns This texture, for chaining.
   */
  public setLevel(level: number, mipmap: CompressedMipmap): this {
    this.levels[level] = mipmap;
    if (level === 0) this.syncLevel(0);
    else this.markNeedsUpdate();
    return this;
  }

  /** Byte size a level *should* have for the current format. */
  public expectedLevelByteSize(level: number = 0): number {
    const mipmap = this.levels[level];
    if (!mipmap) return 0;
    return getCompressedLevelByteSize(this.compressedFormat, mipmap.width, mipmap.height);
  }

  /** `true` when every level's data matches the block layout of the format. */
  public isValid(): boolean {
    for (let i = 0; i < this.levels.length; i++) {
      if (this.expectedLevelByteSize(i) !== this.levels[i].data.byteLength) return false;
    }
    return true;
  }

  /** `true` when the texture has usable compressed blocks. */
  public override isReady(): boolean {
    const first = this.levels[0];
    return !this.isDisposed && first !== undefined && first.data.byteLength > 0 && first.width > 0;
  }

  /**
   * `false`: compressed levels cannot be generated by the GPU, only supplied.
   */
  public readonly supportsMipmapGeneration: boolean = false;

  /** Copies the compressed layout and levels of another compressed texture. */
  public override copy(source: Texture): this {
    super.copy(source);
    if (source instanceof CompressedTexture) {
      this.compressedFormat = source.compressedFormat;
      this.setMipmaps(source.levels);
    }
    return this;
  }

  /** Independent copy; block data is shared by reference. */
  public override clone(): this {
    return new (this.constructor as new () => this)().copy(this);
  }

  /** Keeps `image`/`source` pointing at level 0, which `getSize` measures. */
  private syncLevel(level: number): void {
    const mipmap = this.levels[level];
    if (!mipmap) return;
    const source: TextureSource = {
      data: mipmap.data,
      width: mipmap.width,
      height: mipmap.height,
      compressed: true,
    };
    this.image = source;
    this.source = source;
    this.markNeedsUpdate();
  }
}
