/**
 * `RawShaderMaterial` — a shader material with no injected prefix.
 *
 * `ShaderMaterial` lets the backend prepend a version header, a precision block
 * and the standard uniforms/attributes. `RawShaderMaterial` disables all of that:
 * whatever the caller writes is exactly what is compiled, which is what a shader
 * ported from elsewhere (or generated by a tool) needs.
 *
 * ```ts
 * const material = new RawShaderMaterial({ vertexShader, fragmentShader });
 * material.rawShaderMaterial;   // true
 * ```
 *
 * @packageDocumentation
 */

import { Material } from './Material';
import { ShaderMaterial } from './ShaderMaterial';

/**
 * A shader material compiled verbatim.
 */
export class RawShaderMaterial extends ShaderMaterial {
  /** Human-readable label used in diagnostics. */
  public override readonly label: string = 'RawShaderMaterial';

  /** Registered type name. */
  public override readonly type: string = 'RawShaderMaterial';

  /**
   * Brand the backend checks before injecting anything.
   *
   * A property (not a method) so it survives `copy` and can be read off a
   * structurally-typed material.
   */
  public readonly rawShaderMaterial: true = true;

  /** Copies the program from another raw shader material. */
  public override copy(source: Material): this {
    super.copy(source);
    return this;
  }

  /** Independent copy of this material. */
  public override clone(): this {
    return new (this.constructor as new () => this)().copy(this);
  }
}
